### ISSUE TITLE
https://github.com/BoltsFramework/Bolts-iOS.git

### ISSUE THREAD

**Issue by podosvetesi** [BoltsFramework/Bolts-iOS#108]
Please help me, Facebook says: "The Bolts Framework , which is included in Facebook SDK, provides easy to use APIs to help you to parse the incoming URL." Thank you!
Ourapp's url: https://itunes.apple.com/hu/app/iptvhungary/id999802622?mt=8

**Comment by nlutsenko** [comment]
@podosvetesi 
Is there something that you are looking for specifically?
The question is quite broad, but it looks like you are looking for `http://applinks.org` reference, since it's related to parsing incoming URLs. Bolts.framework can indeed help you with that. Take a look at the website, it has some good examples on the usage as well as guides for implementing this in your app.
(also feel free to reopen or open a new issue if you have any questions)
